# Config for EleutherEvalRecipe in eleuther_eval.py
#
# To launch, run the following command from root torchtune directory:
#    tune run eleuther_eval --config eleuther_evaluation tasks=["truthfulqa_mc2","hellaswag"]

output_dir: ./outputs_llama_3_2_1b_orig/ # Not needed

# Model Arguments
model:
  _component_: torchtune.models.llama3_2.llama3_2_1b

checkpointer:
  _component_: torchtune.training.FullModelHFCheckpointer
  checkpoint_dir: ./tmp/llama_3_2_1b/
  checkpoint_files: [
    model.safetensors,
  ]
  output_dir: ${output_dir}
  model_type: LLAMA3_2

# Tokenizer
tokenizer:
  _component_: torchtune.models.llama3.llama3_tokenizer
  path: ./tmp/llama_3_2_1b/original/tokenizer.model
  max_seq_len: null

# Environment
device: cuda
dtype: fp16
seed: 1234 # It is not recommended to change this seed, b/c it matches EleutherAI's default seed

# EleutherAI specific eval args
tasks: ["truthfulqa_mc2", "gsm8k", "hellaswag", "wikitext", "arc_challenge", "humaneval", "mgsm_direct_en", "mmlu", "squadv2", "winogrande"]
limit: null
max_seq_length: 4096
batch_size: 1
enable_kv_cache: True

# Quantization specific args
quantizer: null
